on: [push]
name: CI
jobs:
  build_and_test:
    name: RPrime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: i 23
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: i 28
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: n 24
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: n lol
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: i lol
